// Generated by SugarLisp v0.5
var dnode = require('dnode');


var remote = {
  transform: function(s, cb) {
    console.log("I got beeped!");
    return cb(null, (s.replace(/[aeiou]{2,}/, 'oo').toUpperCase()))
  }
};

var server = dnode(remote);
server.listen(5004);
console.log("Listening for beeps...");