// Generated by SugarLisp v0.5
var http = require("http");

var server = http.createServer(function(request, response) {
  response.writeHead(200, {
    'Content-Type': 'text/plain'
  });
  return response.end("Hello World\n");
});

server.listen(3000, "localhost");
console.log("Server running at http://localhost:3000/");