// Generated by SugarLisp v0.5
(3000. listen(((function(request, response) {
  response.writeHead(200, {
    'Content-Type': 'text/plain'
  });
  return response.end("Hello World\n");
}.createServer)(require("http")))))
"localhost";