// Generated by SugarLisp v0.5
var fs = require("fs");
var http = require("http");

var requestHandler = function(request, response) {
  return (function() {
    var filename = null;
    if ((request.url === "/")) {
      filename = "index.html"
    } else {
      filename = request.url.substr(1)
    };
    response.setHeader("Content-Type", "text/html");
    var next = null;
    var ___curr = -1;
    var ___actions = [
      function() {
        return fs.exists(filename, next());
      },
      function(exists) {
        if (exists) {
          fs.readFile(filename, "utf8", next())
        } else {
          response.end("File Not Found")
        };
      },
      function(err, data) {
        if (err) {
          response.end("Internal Server Error")
        } else {
          response.end(data)
        };
      }
    ];
    next = function() {
      var ne = ___actions[++___curr];
      return (ne ?
        ne :
        (function() {
          throw "Call to (next) beyond sequence.";
        })());
    };
    return (next())();
  })();
};

var server = http.createServer(requestHandler);
server.listen(3000, "localhost");
console.log("Server running at http://localhost:3000/");